-- MySQL Script generated by MySQL Workbench
-- Tue May 13 01:29:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instituicao` (
  `id` INT NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  `ano_de_fundacao` YEAR NOT NULL,
  `area_de_atuacao` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conferencia_cientifica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conferencia_cientifica` (
  `nome` VARCHAR(100) NOT NULL,
  `edicao` VARCHAR(10) NOT NULL,
  `data_do_evento` DATE NOT NULL,
  `quantidade_max_de_artigos` INT NOT NULL,
  `pais` VARCHAR(30) NOT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `bairro` VARCHAR(45) NULL,
  `rua` VARCHAR(40) NOT NULL,
  `estado_provincia_regiao` VARCHAR(30) NULL,
  `numero` INT NULL,
  `instituicao_id` INT NOT NULL,
  PRIMARY KEY (`nome`, `edicao`),
  INDEX `instituicao_id_idx` (`instituicao_id` ASC) VISIBLE,
  CONSTRAINT `instituicao_id`
    FOREIGN KEY (`instituicao_id`)
    REFERENCES `mydb`.`instituicao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`principais_topicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`principais_topicos` (
  `topico` VARCHAR(20) NOT NULL,
  `conferencia_nome` VARCHAR(100) NOT NULL,
  `conferencia_edicao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`topico`, `conferencia_nome`, `conferencia_edicao`),
  INDEX `conferencia_idx` (`conferencia_nome` ASC, `conferencia_edicao` ASC) VISIBLE,
  CONSTRAINT `conferencia`
    FOREIGN KEY (`conferencia_nome` , `conferencia_edicao`)
    REFERENCES `mydb`.`conferencia_cientifica` (`nome` , `edicao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `id` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `nome_completo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artigo_cientifico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artigo_cientifico` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(200) NOT NULL,
  `resumo` TEXT NOT NULL,
  `numero_de_paginas` INT NOT NULL,
  `tipo_de_apresentacao` ENUM('oral', 'poster') NOT NULL,
  `idioma` VARCHAR(10) NOT NULL,
  `link` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`palavras_chave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`palavras_chave` (
  `palavras_chave` VARCHAR(20) NOT NULL,
  `artigo_id` INT NOT NULL,
  PRIMARY KEY (`palavras_chave`),
  INDEX `artigo_id_idx` (`artigo_id` ASC) VISIBLE,
  CONSTRAINT `artigo_id`
    FOREIGN KEY (`artigo_id`)
    REFERENCES `mydb`.`artigo_cientifico` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`criterio_avaliativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`criterio_avaliativo` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `conferencia_nome` VARCHAR(20) NOT NULL,
  `conferencia_edicao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `conferencia_idx` (`conferencia_nome` ASC, `conferencia_edicao` ASC) VISIBLE,
  CONSTRAINT `conferencia`
    FOREIGN KEY (`conferencia_nome` , `conferencia_edicao`)
    REFERENCES `mydb`.`conferencia_cientifica` (`nome` , `edicao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organizador` (
  `numero_de_registro` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `nome_completo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`numero_de_registro`),
  UNIQUE INDEX `numero_de_registro_UNIQUE` (`numero_de_registro` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`revisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`revisor` (
  `numero_de_registro` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `nome_completo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`numero_de_registro`),
  UNIQUE INDEX `numero_de_registro_UNIQUE` (`numero_de_registro` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`coordenador` (
  `numero_de_registro` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `nome_completo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`numero_de_registro`),
  UNIQUE INDEX `numero_de_registro_UNIQUE` (`numero_de_registro` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`afiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`afiliar` (
  `instituicao_id` INT NOT NULL,
  `autor_id` INT NOT NULL,
  PRIMARY KEY (`instituicao_id`, `autor_id`),
  INDEX `autor_idx` (`autor_id` ASC) VISIBLE,
  CONSTRAINT `instituicao`
    FOREIGN KEY (`instituicao_id`)
    REFERENCES `mydb`.`instituicao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `autor`
    FOREIGN KEY (`autor_id`)
    REFERENCES `mydb`.`autor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coordenar_revisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`coordenar_revisor` (
  `coordenador_id` INT NOT NULL,
  `revisor_id` INT NOT NULL,
  PRIMARY KEY (`coordenador_id`, `revisor_id`),
  INDEX `revisor_idx` (`revisor_id` ASC) VISIBLE,
  CONSTRAINT `coordenador`
    FOREIGN KEY (`coordenador_id`)
    REFERENCES `mydb`.`coordenador` (`numero_de_registro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `revisor`
    FOREIGN KEY (`revisor_id`)
    REFERENCES `mydb`.`revisor` (`numero_de_registro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coordenar_coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`coordenar_coordenador` (
  `coordenador_superior_id` INT NOT NULL,
  `coordenador_id` INT NOT NULL,
  PRIMARY KEY (`coordenador_superior_id`, `coordenador_id`),
  INDEX `coordenador2_idx` (`coordenador_id` ASC) VISIBLE,
  CONSTRAINT `coordenador1`
    FOREIGN KEY (`coordenador_superior_id`)
    REFERENCES `mydb`.`coordenador` (`numero_de_registro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `coordenador2`
    FOREIGN KEY (`coordenador_id`)
    REFERENCES `mydb`.`coordenador` (`numero_de_registro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coordenar_organizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`coordenar_organizador` (
  `coordenador_id` INT NOT NULL,
  `organizador_id` INT NOT NULL,
  PRIMARY KEY (`coordenador_id`, `organizador_id`),
  INDEX `organizador_idx` (`organizador_id` ASC) VISIBLE,
  CONSTRAINT `coordenador`
    FOREIGN KEY (`coordenador_id`)
    REFERENCES `mydb`.`coordenador` (`numero_de_registro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `organizador`
    FOREIGN KEY (`organizador_id`)
    REFERENCES `mydb`.`organizador` (`numero_de_registro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vincular_coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vincular_coordenador` (
  `coordenador_id` INT NOT NULL,
  `instituicao_id` INT NOT NULL,
  PRIMARY KEY (`coordenador_id`, `instituicao_id`),
  INDEX `instituicao_idx` (`instituicao_id` ASC) VISIBLE,
  CONSTRAINT `coordenador`
    FOREIGN KEY (`coordenador_id`)
    REFERENCES `mydb`.`coordenador` (`numero_de_registro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `instituicao`
    FOREIGN KEY (`instituicao_id`)
    REFERENCES `mydb`.`instituicao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vincular_revisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vincular_revisor` (
  `revisor_id` INT NOT NULL,
  `instituicao_id` INT NOT NULL,
  PRIMARY KEY (`revisor_id`, `instituicao_id`),
  INDEX `instituicao_idx` (`instituicao_id` ASC) VISIBLE,
  CONSTRAINT `revisor`
    FOREIGN KEY (`revisor_id`)
    REFERENCES `mydb`.`revisor` (`numero_de_registro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `instituicao`
    FOREIGN KEY (`instituicao_id`)
    REFERENCES `mydb`.`instituicao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vincular_organizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vincular_organizador` (
  `organizador_id` INT NOT NULL,
  `instituicao_id` INT NOT NULL,
  PRIMARY KEY (`organizador_id`, `instituicao_id`),
  INDEX `instituicao_idx` (`instituicao_id` ASC) VISIBLE,
  CONSTRAINT `organizador`
    FOREIGN KEY (`organizador_id`)
    REFERENCES `mydb`.`organizador` (`numero_de_registro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `instituicao`
    FOREIGN KEY (`instituicao_id`)
    REFERENCES `mydb`.`instituicao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`escrever`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`escrever` (
  `autor_id` INT NOT NULL,
  `artigo_id` INT NOT NULL,
  PRIMARY KEY (`autor_id`, `artigo_id`),
  INDEX `artigo_idx` (`artigo_id` ASC) VISIBLE,
  CONSTRAINT `autor`
    FOREIGN KEY (`autor_id`)
    REFERENCES `mydb`.`autor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `artigo`
    FOREIGN KEY (`artigo_id`)
    REFERENCES `mydb`.`artigo_cientifico` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`submeter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`submeter` (
  `artigo_id` INT NOT NULL,
  `revisor_id` INT NOT NULL,
  `criterio_id` INT NOT NULL,
  `conferencia_nome` VARCHAR(20) NOT NULL,
  `conferencia_edicao` VARCHAR(10) NOT NULL,
  `nota` FLOAT NOT NULL,
  `data_avaliacao_final` DATE NOT NULL,
  `status` ENUM('rejeitado', 'aceito', 'em avaliacao') NOT NULL,
  `data_submissao` DATE NOT NULL,
  PRIMARY KEY (`artigo_id`, `revisor_id`, `criterio_id`, `conferencia_nome`, `conferencia_edicao`),
  INDEX `revisor_idx` (`revisor_id` ASC) VISIBLE,
  INDEX `criterio_idx` (`criterio_id` ASC) VISIBLE,
  INDEX `conferencia_idx` (`conferencia_nome` ASC, `conferencia_edicao` ASC) VISIBLE,
  CONSTRAINT `artigo`
    FOREIGN KEY (`artigo_id`)
    REFERENCES `mydb`.`artigo_cientifico` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `revisor`
    FOREIGN KEY (`revisor_id`)
    REFERENCES `mydb`.`revisor` (`numero_de_registro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `criterio`
    FOREIGN KEY (`criterio_id`)
    REFERENCES `mydb`.`criterio_avaliativo` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `conferencia`
    FOREIGN KEY (`conferencia_nome` , `conferencia_edicao`)
    REFERENCES `mydb`.`conferencia_cientifica` (`nome` , `edicao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
